id: P009433
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG25518
  title: བྱིས་གླུ།
  author: ''
  volumes:
    139d4d9ef9df4863ae24012677b74ec8:
      image_group_id: I1KG25520
      title: ''
      volume_number: 1
      total_pages: 128
